In [64]:
## Training Pipeline

## Plan of Attack:

1. We will build a simple neural network: Only one neuron

2. Train it on a real world dataset: breast cancer dataset

3. Will mimic the PyTorch Workflow

4. Will have a lot of manual elements: loss_fn,gradient descent

5. End result is not important

## Code Flow

1.Load the dataset (load from github)

2.Basic preprocessing (scaling,encoding)

3.Training process:
    a. Create the model
    will have 30 input features and one
    
    b.Forward pass
    cal y_pred

    c.Loss cal

    d.Backprop

    e.Parameters update

4. Model evaluation

In [65]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [66]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [67]:
df.shape ## 569 rows and 33 columns

(569, 33)

In [68]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

## Train Test Split

In [69]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],random_state=42,test_size=0.2)

## Scaling

In [70]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [71]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [72]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [15]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [16]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

## Numpy Arrays to pytorch

In [73]:
import torch
X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)

In [19]:
X_train.shape

torch.Size([455, 30])

In [20]:
y_train.shape

torch.Size([455])

## Creating and defining a neural network

In [75]:
## no of weights= no of input features
class MySimpleNN():

  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)


  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_binary_cross_entropy(self,y_pred,y):
    epsilon=1e-7 ## to avoid log(0) error
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss= -(y * torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
    return loss

## Important Parameters

In [76]:
learning_rate=0.1
epochs=25

## Training Pipeline

In [77]:
## create a model

model=MySimpleNN(X_train)

model.weights

tensor([[0.0037],
        [0.9102],
        [0.3975],
        [0.7833],
        [0.6793],
        [0.7484],
        [0.6772],
        [0.2899],
        [0.9598],
        [0.6196],
        [0.4359],
        [0.8648],
        [0.2626],
        [0.2626],
        [0.1419],
        [0.7939],
        [0.7257],
        [0.0156],
        [0.1114],
        [0.5706],
        [0.2943],
        [0.2560],
        [0.5946],
        [0.6359],
        [0.0824],
        [0.2483],
        [0.7590],
        [0.7180],
        [0.4823],
        [0.8362]], dtype=torch.float64, requires_grad=True)

In [51]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [78]:
## these all will be done in a loop which is epoch times


for epoch in range(epochs):
  ## Forward pass
  y_pred=model.forward(X_train)      ## X_train shape:455 X 30 and weights shape: 30 X 1         x_train X weights= 455 X 1

  ## loss val
  loss=model.loss_binary_cross_entropy(y_pred,y_train)
  print(f'Epoch:{epoch+1},Loss:{loss.item()}')
  ## if we try to print loss we get something like this tensor(0.8631, dtype=torch.float64, grad_fn=<NegBackward0>)
  ## What does loss.item() do? .item() extracts the actual numerical value from a tensor that contains a single element. which is float only not tensor

  ## back pass
  loss.backward()

  ## update weights and biases (parameters)
  ## in this we don't need to cal gradients
  with torch.no_grad():
    model.weights-=learning_rate*(model.weights.grad)
    model.bias-=learning_rate*(model.bias.grad)


  ## zero_gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

Epoch:1,Loss:3.7038274110145606
Epoch:2,Loss:3.5767715648789875
Epoch:3,Loss:3.4482492476597173
Epoch:4,Loss:3.3176755996450655
Epoch:5,Loss:3.184269626236525
Epoch:6,Loss:3.0442069987539497
Epoch:7,Loss:2.8953282610572186
Epoch:8,Loss:2.740914645465547
Epoch:9,Loss:2.5859003986285494
Epoch:10,Loss:2.429380347321365
Epoch:11,Loss:2.273730227952162
Epoch:12,Loss:2.1172586551316286
Epoch:13,Loss:1.9571386709343037
Epoch:14,Loss:1.801904357998318
Epoch:15,Loss:1.6550057034108834
Epoch:16,Loss:1.5144373724780105
Epoch:17,Loss:1.3842426628289766
Epoch:18,Loss:1.2677233274370376
Epoch:19,Loss:1.166003870278892
Epoch:20,Loss:1.0796902913130686
Epoch:21,Loss:1.0085061853529154
Epoch:22,Loss:0.9512044153248692
Epoch:23,Loss:0.9058393557771645
Epoch:24,Loss:0.8701803055590118
Epoch:25,Loss:0.8420884061584267

## Evaluvation

In [83]:
## model evaluvation


with torch.no_grad():
  y_pred=model.forward(X_test)

print(y_pred)


## we need to decide a threshold

tensor([[0.4671],
        [0.1751],
        [0.2959],
        [0.6597],
        [0.6046],
        [0.9007],
        [0.3191],
        [0.2049],
        [0.3880],
        [0.3113],
        [0.4884],
        [0.3440],
        [0.2888],
        [0.6878],
        [0.1461],
        [0.8816],
        [0.1276],
        [0.6922],
        [0.7667],
        [0.5151],
        [0.2558],
        [0.5440],
        [0.6278],
        [0.6001],
        [0.7816],
        [0.5303],
        [0.1528],
        [0.7261],
        [0.4161],
        [0.7177],
        [0.8300],
        [0.1853],
        [0.8229],
        [0.2553],
        [0.5818],
        [0.3832],
        [0.4366],
        [0.2550],
        [0.3021],
        [0.4807],
        [0.7953],
        [0.4685],
        [0.2558],
        [0.3141],
        [0.4312],
        [0.2840],
        [0.4476],
        [0.9381],
        [0.4747],
        [0.3136],
        [0.3004],
        [0.7731],
        [0.6723],
        [0.5396],
        [0.6033],
        [0.1183],
        [0.5967],
        [0.5525],
        [0.3022],
        [0.1939],
        [0.4030],
        [0.3094],
        [0.2106],
        [0.4988],
        [0.3842],
        [0.4841],
        [0.7380],
        [0.9197],
        [0.5178],
        [0.4546],
        [0.5528],
        [0.3265],
        [0.3884],
        [0.4119],
        [0.8829],
        [0.2713],
        [0.3711],
        [0.2596],
        [0.2626],
        [0.3753],
        [0.6066],
        [0.3610],
        [0.7104],
        [0.6521],
        [0.4436],
        [0.6349],
        [0.9499],
        [0.7530],
        [0.4865],
        [0.2195],
        [0.5396],
        [0.2764],
        [0.3780],
        [0.9290],
        [0.6433],
        [0.4279],
        [0.7622],
        [0.7279],
        [0.2063],
        [0.3367],
        [0.2882],
        [0.3880],
        [0.2811],
        [0.3289],
        [0.8010],
        [0.4235],
        [0.6010],
        [0.1097],
        [0.1765],
        [0.1956],
        [0.1205],
        [0.3334],
        [0.7571],
        [0.7426]], dtype=torch.float64)

In [86]:
## model evaluvation


with torch.no_grad():
  y_pred=model.forward(X_test)
  y_pred=(y_pred>0.5).float() ## converts the boolean torch.bool to torch.float
  accuracy=(y_pred==y_test).float().mean()
  print(f"accuracy:{accuracy}")


print(y_pred)

accuracy:0.5236995816230774
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])